build:
  image: registry.docker/golang:$$GO_VERSION
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
  commands:
    - >
      if [[ "x$GO_VERSION" == "x1.5" ]] || [[ "x$GO_VERSION" == "x1.6" ]]; then
        if [[ "x$PLATFORM" == "xcross" ]] || [[ "x$PLATFORM" == "xwheezy" ]]; then
          export SKIP="true";
        fi
      fi

    - >
      if [[ "x$GO_VERSION" == "x1.4" ]]; then
        export GO_VERSION_PATCH="1.4.3";
      elif [[ "x$GO_VERSION" == "x1.5" ]]; then
        export GO_VERSION_PATCH="1.5.4";
      elif [[ "x$GO_VERSION" == "x1.6" ]]; then
        export GO_VERSION_PATCH="1.6.2";
      fi

    - >
      if [[ "x$SKIP" == "xtrue" ]]; then
        echo "Not building golang version $GO_VERSION for platform $PLATFORM";
      else
        echo "Building golang version $GO_VERSION_PATCH for platform $PLATFORM";
      fi

    - >
      if [[ "x$SKIP" != "xtrue" ]] && [[ "x$PLATFORM" == "xnone" ]]; then
        export DIR="$GO_VERSION";
        export TAG="$GO_VERSION";
      else
        export DIR="$GO_VERSION/$PLATFORM";
        export TAG="$GO_VERSION-$PLATFORM";
      fi
    - >
      if [[ "x$SKIP" != "xtrue" ]]; then
        docker build -t registry.docker/golang:$GO_VERSION_PATCH $DIR
        docker tag -f registry.docker/golang:$GO_VERSION_PATCH registry.docker/golang:$TAG
      fi
    - >
      if [[ "x$SKIP" != "xtrue" ]] && [[ "x$GO_VERSION" == "x$GO_VERSION_LATEST" ]]; then
        export MAJOR=`echo $GO_VERSION | cut -d"." -f1`;
        docker tag -f registry.docker/golang:$GO_VERSION_PATCH registry.docker/golang:$PLATFORM;
        docker tag -f registry.docker/golang:$GO_VERSION_PATCH registry.docker/golang:$MAJOR-$PLATFORM;
        if [[ "x$PLATFORM" == "xnone" ]]; then
          docker tag -f registry.docker/golang:$GO_VERSION_PATCH registry.docker/golang:$MAJOR;
          docker tag -f registry.docker/golang:$GO_VERSION_PATCH registry.docker/golang:latest;
        fi
      fi
    # - docker push registry.docker/golang

matrix:
  GO_VERSION:
    - 1.6
    - 1.5
    - 1.4
  GO_VERSION_LATEST:
    - 1.5
  PLATFORM:
    - none
    - cross
    - onbuild
    - swig
    - wheezy
