image: registry.docker/buildpack-deps:scm
volumes:
  - /var/run/docker.sock
script:
  - docker build -t registry.docker/golang:1.3.3 1.3
  - docker tag -f registry.docker/golang:1.3.3 registry.docker/golang:1.3
  - docker build -t registry.docker/golang:1.3.3-onbuild 1.3/onbuild
  - docker tag -f registry.docker/golang:1.3.3-onbuild registry.docker/golang:1.3-onbuild
  - docker build -t registry.docker/golang:1.3.3-cross 1.3/cross
  - docker tag -f registry.docker/golang:1.3.3-cross registry.docker/golang:1.3-cross
  - docker build -t registry.docker/golang:1.3.3-wheezy 1.3/wheezy
  - docker tag -f registry.docker/golang:1.3.3-wheezy registry.docker/golang:1.3-wheezy
  - docker build -t registry.docker/golang:1.4.1 1.4
  - docker tag -f registry.docker/golang:1.4.1 registry.docker/golang:1.4
  - docker tag -f registry.docker/golang:1.4.1 registry.docker/golang:1
  - docker tag -f registry.docker/golang:1.4.1 registry.docker/golang:latest
  - docker build -t registry.docker/golang:1.4.1-onbuild 1.4/onbuild
  - docker tag -f registry.docker/golang:1.4.1-onbuild registry.docker/golang:1.4-onbuild
  - docker tag -f registry.docker/golang:1.4.1-onbuild registry.docker/golang:1-onbuild
  - docker tag -f registry.docker/golang:1.4.1-onbuild registry.docker/golang:onbuild
  - docker build -t registry.docker/golang:1.4.1-cross 1.4/cross
  - docker tag -f registry.docker/golang:1.4.1-cross registry.docker/golang:1.4-cross
  - docker tag -f registry.docker/golang:1.4.1-cross registry.docker/golang:1-cross
  - docker tag -f registry.docker/golang:1.4.1-cross registry.docker/golang:cross
  - docker build -t registry.docker/golang:1.4.1-wheezy 1.4/wheezy
  - docker tag -f registry.docker/golang:1.4.1-wheezy registry.docker/golang:1.4-wheezy
  - docker tag -f registry.docker/golang:1.4.1-wheezy registry.docker/golang:1-wheezy
  - docker tag -f registry.docker/golang:1.4.1-wheezy registry.docker/golang:wheezy
  - docker push registry.docker/golang
