image: registry.docker/buildpack-deps:scm
volumes:
  - /var/run/docker.sock
script:
  - docker build -t registry.docker/golang:1.4.3 1.4
  - docker tag -f registry.docker/golang:1.4.3 registry.docker/golang:1.4
  - docker build -t registry.docker/golang:1.4.3-onbuild 1.4/onbuild
  - docker tag -f registry.docker/golang:1.4.3-onbuild registry.docker/golang:1.4-onbuild
  - docker build -t registry.docker/golang:1.4.3-cross 1.4/cross
  - docker tag -f registry.docker/golang:1.4.3-cross registry.docker/golang:1.4-cross
  - docker build -t registry.docker/golang:1.4.3-wheezy 1.4/wheezy
  - docker tag -f registry.docker/golang:1.4.3-wheezy registry.docker/golang:1.4-wheezy
  - docker build -t registry.docker/golang:1.4.3-swig 1.4/swig
  - docker tag -f registry.docker/golang:1.4.3-swig registry.docker/golang:1.4-swig

  - docker build -t registry.docker/golang:1.5.4 1.5
  - docker tag -f registry.docker/golang:1.5.4 registry.docker/golang:1.5
  - docker tag -f registry.docker/golang:1.5.4 registry.docker/golang:1.5
  - docker tag -f registry.docker/golang:1.5.4 registry.docker/golang:1
  - docker tag -f registry.docker/golang:1.5.4 registry.docker/golang:latest

  - docker build -t registry.docker/golang:1.5.4-onbuild 1.5/onbuild
  - docker tag -f registry.docker/golang:1.5.4-onbuild registry.docker/golang:1.5-onbuild
  - docker tag -f registry.docker/golang:1.5.4-onbuild registry.docker/golang:1-onbuild
  - docker tag -f registry.docker/golang:1.5.4-onbuild registry.docker/golang:onbuild

  - docker build -t registry.docker/golang:1.5.4-swig 1.5/swig
  - docker tag -f registry.docker/golang:1.5.4-swig registry.docker/golang:1.5-swig
  - docker tag -f registry.docker/golang:1.5.4-swig registry.docker/golang:1-swig
  - docker tag -f registry.docker/golang:1.5.4-swig registry.docker/golang:swig

  - docker build -t registry.docker/golang:1.6.1 1.6
  - docker tag -f registry.docker/golang:1.6.1 registry.docker/golang:1.6

  - docker build -t registry.docker/golang:1.6.1-onbuild 1.6/onbuild
  - docker tag -f registry.docker/golang:1.6.1-onbuild registry.docker/golang:1.6-onbuild

  - docker build -t registry.docker/golang:1.6.1-swig 1.6/swig
  - docker tag -f registry.docker/golang:1.6.1-swig registry.docker/golang:1.6-swig

  - docker push registry.docker/golang

